name: Auto-Publish
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  main:
    name: Compile and deploy
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run bikeshed
        run: |
          bikeshed --version
          bikeshed spec
          mkdir dist
          cp *.html dist
          cp -r images dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
