name: Check PR
on:
    pull_request:

jobs:
  master:
    name: Run checks for specification
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run bikeshed
        run: |
            bikeshed --version
            bikeshed spec
